name: Multi-arch Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/dnsmgr

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 代码检出
      - name: Checkout repository
        uses: actions/checkout@v4

      # 多架构构建前置条件
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64  # 启用ARM和AMD架构支持[3]

      # 配置Buildx构建器
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      # Docker Hub认证（关键修正点）
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 多架构构建与推送
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64  # 指定目标架构[3]
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          no-cache: true  # 彻底禁用构建缓存[5]
          secrets: |
            "dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}"
            "dockerhub_token=${{ secrets.DOCKERHUB_TOKEN }}"
            
