name: Multi-arch Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 启用QEMU虚拟化支持（关键前置条件）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64  # 明确指定需虚拟化的架构[<sup>3</sup>](https://www.cloudnative101.net/posts/docker-multi-architecture-building-challenges/)

      # 配置Buildx构建器（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      # 多架构构建核心步骤（禁用缓存）
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64  # 同时构建两种架构镜像[<sup>3</sup>](https://www.cloudnative101.net/posts/docker-multi-architecture-building-challenges/)
          push: true
          tags: your-dockerhub-username/image-name:latest
          no-cache: true  # 强制禁用所有构建缓存[<sup>5</sup>](https://zhengjiabo.github.io/blog/docker/6+-+构建缓存优化技术及多阶段构建.html)
          provenance: false  # 关闭元数据生成（可选）
